### ISSUE TITLE
coverage result all 0

### ISSUE THREAD

**Issue by jingyuezijing** [Codeception/c3#76]
**codeception.yml like this:**
coverage:
    enable: true
    remote: true
    c3_url: 'https://test.connectedpdf.com/index.php/' 

**api.suit.yml like this:**
actor: ApiTester
modules:
    enabled:
        - REST:
            url: 'http://test.connectedpdf.com'
            depends: PhpBrowser
            part: Json
coverage:
   remote: true

**index.php**
add require
require_once __DIR__.'/../../c3.php';
define('MY_APP_STARTED', true);

when i test in command:
php vendor/codeception/codeception/codecept run --coverage --coverage-xml --coverage-html

_output/coverage:open the html ，nothing to test result all zero；how can t do to get the right coverage？
![image](https://user-images.githubusercontent.com/77383326/151322801-5b4cfdcd-1ace-4391-b759-099df9691a48.png)

**Comment by delboy1978uk** [comment]
I'm having a similar issue, I'm running in a docker compose setup using Selenium.
codeception yaml
```
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    remote: true
    include:
        - src/*

```
acceptance yaml
```
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
              host: 'chrome'
              url: 'http://customs.docker'
              browser: chrome
              capabilities:
                  acceptInsecureCerts: true
                  chromeOptions:
                      args: ["--headless", "--disable-gpu"]
        - \Helper\Acceptance
step_decorators: ~
```
public/index.php
```php
$_SERVER['HTTP_X_CODECEPTION_CODECOVERAGE'] = \getenv('APP_ENV') === 'test' ? true : false;
include __DIR__ . '/../c3.php';
```
<img width="620" alt="image" src="https://github.com/Codeception/c3/assets/2684575/6e0d2a73-9b37-494d-b01e-2bcf2e1770d2">

Any  suggestions?
